---
name: Build

on:
  workflow_dispatch:
  push:
    branches: 
      - feature/cmake

defaults:
  run:
    shell: bash

jobs:

  Build:

    name: ${{ matrix.os }} tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        config: [Debug, Release]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 1
          ref: feature/cmake

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install ninja-build libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev

      - name: Configure CMake
        run: cmake --preset maintainer

      - name: Run build 
        run: cmake --build --preset maintainer --config ${{ matrix.config }}
